apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  generateName: ansible-role-hello-world-
spec:
  podGC:
    strategy: OnPodSuccess # delete pods when workflow is successful
  entrypoint: main
  arguments:
    parameters:
    - name: git_ref_type
      value: branches
    - name: git_version
  templates:
  - name: main
    inputs:
      parameters:
      - name: git_ref_type
      - name: git_version
      - name: upstream_repo
        value: quay.io/bradfordwagner/ansible-role-builder
      - name: upstream_tag
        value: 1.1.1
    dag:
      tasks:
      - name: ansible-role
        arguments:
          parameters:
          - name: git_repo
            value: https://github.com/bradfordwagner/ansible-role-helloworld
          - name: git_version
            value: "{{ inputs.parameters.git_version }}"
          - name: upstream_repo
            value: "{{ inputs.parameters.upstream_repo }}"
          - name: upstream_tag
            value: "{{ inputs.parameters.upstream_tag }}"
          - name: tag_suffix
            value: "-{{ item.platform }}"
          - name: platform
            value: "{{ item.platform }}"
          - name: runtime_platforms
            value: "{{ item.runtime_platforms }}"
          - name: ansible_role
            value: helloworld
        templateRef:
          name: flavor-ansible-role-template
          template: main
        withItems:
        - { platform: alpine_3.13     , runtime_platforms: [linux/amd64, linux/arm64] }
        - { platform: alpine_3.14     , runtime_platforms: [linux/amd64, linux/arm64] }
        - { platform: ubuntu_bionic   , runtime_platforms: [linux/amd64, linux/arm64] }
        - { platform: ubuntu_focal    , runtime_platforms: [linux/amd64, linux/arm64] }
        - { platform: debian_buster   , runtime_platforms: [linux/amd64, linux/arm64] }
        - { platform: debian_bullseye , runtime_platforms: [linux/amd64, linux/arm64] }

